
// QUESTION : 1) Explain the use of JavaScript ( or What you can do using a JavaScript)
// ANSWER: Javascript is ued to add functionality and dynamic to the website

// QUESTION : 2) What is the difference between client-side and server-side?
// ANSWER:   JavaScript, a client-side programming language, to create forms that collect user input. 
//            Server-side development can process this input.

// QUESTION : 3)What is Nodejs?
// ANSWER: It is an server side programming language build on top of js and v8 engine

// QUESTION : 4)Explain Scope in JavaScript
// ANSWER: PLace where block of code is executed is called scope
/* There are three types of Scope
1) GlobalScope
2) function Scope
3) block scope {} */


// QUESTION : 5)JavaScript is asynchronous or synchronous.
// ANSWER:synchronous

// QUESTION : 6)JavaScript is Single-threaded or Multi-threaded.
// ANSWER:Single-threaded

// QUESTION : 7) Explain DOM in your own word.
// ANSWER: DOcument object model , the entire html is made up of object and it is Dom 