

/* 1. What is lexical structure?
ANS: A set of basic rules in programming language about how to write code init.

2. What is Unicode?
ANS:The agreement between the two computers about the correspondence between letters and numbers 

3. Explain all the keywords present in the JavaScript with examples.
ANS: let 
     var
     const
     this
     window
    document

4. What are shorthand operators, explain with a suitable example?
ANS: Shorthand Operators are also used to define the Bitwise Operators.
1)a += b ;      // a = a + b ;  i.e., a = 8 + 6 = 14
2)a -= b ;      // a = a - b ;  i.e., a = 8 - 6 = 2
3)a *= b ;      // a = a * b ;  i.e., a = 8 * 6 = 48
4)a %= b ;      // a = a % b ;  i.e., a = 8 % 6 = 0.48
5)a /= b ;      // a = a / b ;  i.e., a = 8 / 6 = 0.25

5. What is “use Strict” in JavaScript?
ANS: The purpose of "use strict" is to indicate that the code should be executed in "strict mode".
Stict mode is used to prevent you form using undeclared variable in your code
*/



